// Land bitmask for the globe: Natural Earth 110m land (public domain),
// rasterized to a 240x120 equirectangular grid (1.5 degrees per cell).
// Bit i = row * MASK_WIDTH + col, row 0 at 90N, col 0 at 180W.
export const MASK_WIDTH = 240;
export const MASK_HEIGHT = 120;

const MASK_BASE64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAfwAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAPD/z////3EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//8f///w8AAOABgAAAAMADAAAAAAAAAAAAAAAAkPwf/v///wcA" +
  "AB8AAAAAAAA4AAAAAAAAAAAAAAADAOEP/v///wcAAAwAAAAAAAAwAAAAAAAAAAAAAAD8cYwDAP///wcAAAAAAIAHAMD/DwDwAAAA" +
  "AAAAAOAAAAkAAPz//wcAAAAAAGAAAP7/AwAAAAAAAAAAAOB/c/MfAPj//wEAAAAAABjAwP///z/gAAAAAIAAAED+B/P/APD//wEA" +
  "AAAAABjg/v///3//HwAAAPj/A0/8z4fzB/D/fwAAAOAfAADg/v///////wc8A/7///9/w56jB+D/DwAAAPz/Q+z//f//////////" +
  "P/D///////+BP/D/AQAAAP7/5////v//////////GP7//////7/wJ+AfAH8AAH9++P//////////////APD//////88CH8AfAAwA" +
  "wJ////////////////9/APz//////wNwAIAPAAAA8M////////////////8/APz//////wHwAQAGAAAA+I///////////////+AD" +
  "APAD+P///wHwMwAAAAAA8A//////////////ZBgAAIACgP///wPgfwAAAAAwAAf///////////8fAA4AACAAAP///z/gfwAAAAAw" +
  "YMf///////////8PAA8AAAAAAP7////5/wMAAABoQOj///////////8HAA8AAAAAAPz////5/wcAAADs+P////////////9/AAMA" +
  "AAAAAPj////7/wcAAADg/f//////////////AAEAAAAAAPj//////wQAAAAA/v////////////+/AAAAAAAAAPD/////Gw4AAADg" +
  "//////////////8fAAAAAAAAAOD/////HxAAAADA//////////////8fAAAAAAAAAOD//////wAAAACA///P/v////////8PAAAA" +
  "AAAAAOD/////EwAAAACA//0H/P/////////HAAAAAAAAAOD/////AQAAAAD8g/EH+P/////////gAAAAAAAAAOD/////AAAAAAD8" +
  "Aebn+f///////z8gAAAAAAAAAOD///9/AAAAAAD8AGT8/////////xpgAAAAAAAAAMD///8/AAAAAAD8AMD8////////fzAgAAAA" +
  "AAAAAID///8fAAAAAABwfAD4/////////zE4AAAAAAAAAID///8fAAAAAACwfwAA/////////zAfAAAAAAAAAAD+//8PAAAAAAD4" +
  "fwAA/////////4ADAAAAAAAAAAD8//8DAAAAAAD8/8OA/////////4EAAAAAAAAAAADg//8DAAAAAAD8/+///////////wEAAAAA" +
  "AAAAAADo/wkCAAAAAAD+//////z//////wEAAAAAAAAAAADQfwACAAAAAID///////n//////wEAAAAAAAAAAACAfwAGAAAAAID/" +
  "//9//8H//////wAAAAAAAAAAAAAgfwAAAAAAAMD///9//jPg////fwAAAAAAAAAAAAAAfgAAAAAAAOD//////H/A////PwEAAAAA" +
  "AAAAAAAAfAAIAAAAAOD//////f/A/+f/BwAAAAAAAAAAAAAAfDAwAAAAAOD/////+X8A/sN/AgAAAAAAAAAAAAAA+DiAAwAAAOD/" +
  "////+T8A/oB/AAAAAAAAAAAAAAAA4B8AAAAAAOD/////8x8AfoB/AAMAAAAAAAAAAAAAgPwAAAAAAOD/////4wcAPgD+AAEAAAAA" +
  "AAAAAAAAAPgAAAAAAOD/////7wEAHAD+AQIAAAAAAAAAAAAAAMAAAAAAAOD/////PwAAHAD0AQAAAAAAAAAAAAAAAICAAgAAAMD/" +
  "////HwMAHADgAAAAAAAAAAAAAAAAAIDBfwAAAID//////wMAGABAAAAAAAAAAAAAAAAAAAD2/wAAAID//////wEAIAAEAAwAAAAA" +
  "AAAAAAAAAADw/wEAAAD//////wEAIAAIAAgAAAAAAAAAAAAAAADw/x8AAAD8+P///wAAAAAZYAAAAAAAAAAAAAAAAADw/z8AAAAA" +
  "wP///wAAAAAbMAAAAAAAAAAAAAAAAADw/z8AAAAAwP//fwAAAAAWfAAAAAAAAAAAAAAAAAD4/38AAAAAwP//HwAAAAAcfiAAAAAA" +
  "AAAAAAAAAAD8//8AAAAAwP//DwAAAAAYPgABAAAAAAAAAAAAAAD8//8HAAAAwP//BwAAAAA4vgEZAAAAAAAAAAAAAAD8//8/AAAA" +
  "gP//BwAAAABwEAP+IAAAAAAAAAAAAAD8////AAAAAP//AwAAAABgAADwAQAAAAAAAAAAAAD8////AQAAAP//AwAAAACAAADwAwAA" +
  "AAAAAAAAAAD4////AQAAAP7/AwAAAAAADADwBgAAAAAAAAAAAADw////AAAAAP7/BwAAAAAAAAAADAAAAAAAAAAAAADw//9/AAAA" +
  "AP7/BwAAAAAAAAAAAAAAAAAAAAAAAADg//8/AAAAAP7/BwAAAAAAAICHAAAAAAAAAAAAAADg//8/AAAAAP//BwEAAAAAANDHAAAA" +
  "AAAAAAAAAADA//8/AAAAAP//hwEAAAAAAPjHAQAAAAAAAAAAAAAA//8/AAAAAP//4wEAAAAAAPzfAQAAAAAAAAAAAAAA/v8/AAAA" +
  "AP//4AEAAAAAAP7/AwAAAAAAAAAAAAAA/v8fAAAAAP5/wAAAAAAAgP//BwAAAAAAAAAAAAAA/v8fAAAAAP7/4AAAAAAA4P//DwAA" +
  "AAAAAAAAAAAA/v8HAAAAAPz/4AAAAAAA8P//HwAAAAAAAAAAAAAA/v8AAAAAAPx/YAAAAAAA8P//PwAAAAAAAAAAAAAA/v8AAAAA" +
  "APw/AAAAAAAA8P//PwAAAAAAAAAAAAAA/v8AAAAAAPw/AAAAAAAA8P//PwAAAAAAAAAAAAAA/38AAAAAAPgfAAAAAAAA4P//PwAA" +
  "AAAAAAAAAAAA/z8AAAAAAPAPAAAAAAAA4P//PwAAAAAAAAAAAAAA/x8AAAAAAPAHAAAAAAAA4B/+PwAAAAAAAAAAAAAA/w8AAAAA" +
  "APABAAAAAAAA4AP0HwAAAAAAAAAAAAAA/wMAAAAAAAAAAAAAAAAAAADwDwAAAAAAAAAAAACA/wMAAAAAAAAAAAAAAAAAAADgDwAQ" +
  "AAAAAAAAAACA/wEAAAAAAAAAAAAAAAAAAADAAwBwAAAAAAAAAACAfwAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAACAHwAAAAAA" +
  "AAAAAAAAAAAAAAAABgAYAAAAAAAAAACAHwAAAAAAAAAAAAAAAAAAAAAABgAMAAAAAAAAAACADwAAAAAAAAAAAAAAAAAAAAAAAAAD" +
  "AAAAAAAAAADABwAAAAAAAAAAAAAAAAAAAAAAAIADAAAAAAAAAADADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADABwAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAwAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAACABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAADwAAAR4Pv4HAAAA" +
  "AAAAAAAAAAAAGAAAAAAAAAAA4P8/4P//////BwAAAAAAAAAAAAAAPwAAAAAAAADg//8//P///////wMAAAAAAAAAAACAewAAAABI" +
  "/v////8///////////8BAAAAAAAAcAAAeQAAAID///////////////////8DAAAAANAf4P//fwAAAOD//////////////////38A" +
  "AACA////////BwAAAPz//////////////////x8AAIDz//////8/AAAA8P///////////////////x8AABD///////8PAIAH////" +
  "/////////////////z8AAADA//////8/gPAD8P///////////////////wcAAAD+////////P4Dw/////////////////////w8A" +
  "AAD8//////////////////////////////////8A9OD4//////////////////////////////////83AAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

let bits: Uint8Array | null = null;

export const isLand = (lat: number, lon: number) => {
  if (!bits) bits = Uint8Array.from(atob(MASK_BASE64), (c) => c.charCodeAt(0));
  const row = Math.min(MASK_HEIGHT - 1, Math.floor(((90 - lat) / 180) * MASK_HEIGHT));
  const col = Math.min(MASK_WIDTH - 1, Math.floor(((lon + 180) / 360) * MASK_WIDTH));
  const i = row * MASK_WIDTH + col;
  return ((bits[i >> 3] >> (i & 7)) & 1) === 1;
};